import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meu App Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="bg-gray-900 text-white p-4">
          <h2 className="text-lg font-bold">Meu Sistema</h2>

          <nav className="flex gap-4 mt-2">
            <Link href="/">Home</Link>
            <Link href="/dashboard">Dashboard</Link>
            <Link href="/about">Sobre</Link>
          </nav>
        </header>

        <main className="p-5">
          {children}
        </main>

        <footer className="bg-gray-200 p-3">
          <p className="text-gray-800">Rodapé</p>
        </footer>
      </body>
    </html>
  );
}
